import express from "express";
import requestController from "./request.controller.js";
import { singleFile } from '../../middleware/multerConfig.js'; 
import protect from "../../middleware/protectedRoutes.js";
const router = express.Router();
router.post('/addrequest', singleFile('profilepicture', 'requests'), requestController.addrequest);
router.post('/accept/:id', protect(['admin']), requestController.acceptUser);
router.post('/reject/:id', protect(['admin']), requestController.rejectUser);
router.get('/',protect(['admin']), requestController.getAllRequests);
router.get('/requestcount',protect(['admin']), requestController.requestsCount);
export default router;